test_data_path: "/home/justin/code/LieNeurons/data/sl3_inv_5_input_data/sl3_inv_100_s_05_test_data.npz"

# logger
model_description: "SL3InvariantFunctionFitting"

print_freq: 100

model_type: "LN"
model_path: "/home/justin/code/LieNeurons/weights/0925_sl3_inv_5_input_LN_256_no_share_nonlin_train_100_lr_0.0000003_best_test_loss_acc.pt"

# model_type: "MLP"
# model_path: "/home/justin/code/LieNeurons/weights/0925_sl3_inv_5_input_MLP_256_share_nonlin_train_100_best_test_loss_acc.pt"
num_workers: 1

batch_size: 10
shuffle: True

