test_data_path: "/home/justin/code/LieNeurons/data/sl3_inv_data/sl3_inv_10000_s_05_test_data.npz"

# logger
model_description: "SL3InvariantFunctionFitting"

print_freq: 100

model_type: "LN"
model_path: "/home/justin/code/LieNeurons/weights/0928_sl3_inv_LN_256_no_share_nonlin_train_10000_lr_0.000003_new_best_test_loss_acc.pt"

# model_type: "MLP"
# model_path: "/home/justin/code/LieNeurons/weights/0928_sl3_inv_MLP_256_no_share_nonlin_train_1000_lr_0.00001_best_test_loss_acc.pt"
num_workers: 1

batch_size: 100
shuffle: True

