test_data_path: "/home/justin/code/LieNeurons/data/sl3_inv_data/sl3_inv_100_s_05_test_data.npz"

# logger
model_description: "SL3InvariantFunctionFitting"

print_freq: 100
model_path: "/home/justin/code/LieNeurons/weights/0923_sl3_inv_LN_256_no_share_nonlin_batch_n_train_100000.pth.tar"

num_workers: 1

batch_size: 1000
update_every_batch: 1
initial_learning_rate: 0.00003
learning_rate_decay_rate: 0.0
weight_decay_rate: 0.00
num_epochs: 500
shuffle: True

