train_data_path: "/home/justin/code/LieNeurons/data/sl3_inv_data/sl3_inv_train_data.npz"
test_data_path: "/home/justin/code/LieNeurons/data/sl3_inv_data/sl3_inv_test_data.npz"

# logger
model_description: "SL3InvariantFunctionFitting"

print_freq: 100
model_save_path: "/home/justin/code/LieNeurons/weights/0921_sl3_inv_first_try"
log_writer_path: "/home/justin/code/LieNeurons/logs/0921_sl3_inv_first_try"

resume_training: false
resume_model_path: "/home/justin/code/LieNeurons/weights/0921_sl3_inv_first_try.pth.tar"

num_workers: 1

batch_size: 10
update_every_batch: 1
initial_learning_rate: 0.001
learning_rate_decay_rate: 0.01
weight_decay_rate: 0.0
num_epochs: 5000
shuffle: True

