# train_data_path: "/home/justin/code/LieNeurons/data/sl3_inv_data/sl3_inv_10000_s_05_train_data.npz"
# test_data_path: "/home/justin/code/LieNeurons/data/sl3_inv_data/sl3_inv_10000_s_05_test_data.npz"
train_data_path: "/home/justin/code/LieNeurons/data/sl3_inv_data/sl3_inv_10000_s_05_train_data.npz"
test_data_path: "/home/justin/code/LieNeurons/data/sl3_inv_data/sl3_inv_10000_s_05_test_data.npz"
# logger
model_description: "SL3InvariantFunctionFitting"

print_freq: 100

model_type: "LN"
model_save_path: "/home/justin/code/LieNeurons/weights/0928_sl3_inv_LN_256_no_share_nonlin_train_10000_lr_0.000003_new"
log_writer_path: "/home/justin/code/LieNeurons/logs/0928_sl3_inv_LN_256_no_share_nonlin_train_10000_lr_0.000003_new"

# model_type: "MLP"
# model_save_path: "/home/justin/code/LieNeurons/weights/0928_sl3_inv_MLP_256_no_share_nonlin_train_1000_lr_0.00001"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0928_sl3_inv_MLP_256_no_share_nonlin_train_1000_lr_0.00001"


resume_training: false
resume_model_path: "/home/justin/code/LieNeurons/weights/0921_sl3_inv_first_try.pth.tar"

num_workers: 1

batch_size: 100
update_every_batch: 1
initial_learning_rate: 0.000003
learning_rate_decay_rate: 0.0
weight_decay_rate: 0.00
num_epochs: 2000
shuffle: True

