# train_data_path: "/home/justin/code/LieNeurons/data/sl3_inv_data/sl3_inv_10000_s_05_train_data.npz"
# test_data_path: "/home/justin/code/LieNeurons/data/sl3_inv_data/sl3_inv_10000_s_05_test_data.npz"
train_data_path: "/home/justin/code/LieNeurons/data/sl3_inv_data/sl3_inv_10000_s_05_train_data.npz"
test_data_path: "/home/justin/code/LieNeurons/data/sl3_inv_data/sl3_inv_10000_s_05_test_data.npz"
# logger
model_description: "SL3InvariantFunctionFitting"

print_freq: 100

# model_type: "LN_relu_bracket"
# model_save_path: "/home/justin/code/LieNeurons/weights/0928_one_relu_one_bracket"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0928_one_relu_one_bracket"

# model_type: "LN_relu"
# model_save_path: "/home/justin/code/LieNeurons/weights/0928_one_relu"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0928_one_relu"

# model_type: "LN_bracket"
# model_save_path: "/home/justin/code/LieNeurons/weights/0928_one_bracket_2"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0928_one_bracket_2"

# model_type: "MLP"
# model_save_path: "/home/justin/code/LieNeurons/weights/0928_MLP"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0928_MLP"

model_type: "LN_bracket_no_residual"
model_save_path: "/home/justin/code/LieNeurons/weights/0928_one_bracket_no_residual"
log_writer_path: "/home/justin/code/LieNeurons/logs/0928_one_bracket_no_residual"

resume_training: false
resume_model_path: "/home/justin/code/LieNeurons/weights/0921_sl3_inv_first_try.pth.tar"

num_workers: 1

batch_size: 100
update_every_batch: 1
# initial_learning_rate: 0.00003
initial_learning_rate: 0.0001
learning_rate_decay_rate: 0.0
weight_decay_rate: 0.00
num_epochs: 2000
shuffle: True

